services:
  app:
    build: .
    container_name: bayeta-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/ 
    networks:
      - red-bayeta

  mongo:
    image: mongo:6
    container_name: bayeta-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - red-bayeta

networks:
  red-bayeta:

volumes:
  mongo_data: